create database RSN;

USE RSN;

CREATE TABLE RASEEN(
CUSTOMERID INT NOT NULL PRIMARY KEY,
FIRSTNAME VARCHAR (50) NOT NULL,
LASTNAME VARCHAR (50) NOT NULL,
AGE INT NOT NULL,
ADDRESS VARCHAR (75) NOT NULL
);

SELECT * FROM RASEEN;

INSERT INTO RASEEN(CUSTOMERID,FIRSTNAME,LASTNAME,AGE,ADDRESS) VALUES(2,'SITHI','NABISA',35,'NAGORE'),(3,'RASEEN','RSN',21,'NAGORE'),(4,'AYISHA','JASMINE',29,'NAGORE');

ALTER TABLE RASEEN
ADD RSNID INT NOT NULL;

ALTER TABLE RASEEN
ALTER COLUMN RSNID INT NOT NULL; 